// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadDbproto returns the embedded CollectionSpec for dbproto.
func loadDbproto() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_DbprotoBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load dbproto: %w", err)
	}

	return spec, err
}

// loadDbprotoObjects loads dbproto and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*dbprotoObjects
//	*dbprotoPrograms
//	*dbprotoMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadDbprotoObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadDbproto()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// dbprotoSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dbprotoSpecs struct {
	dbprotoProgramSpecs
	dbprotoMapSpecs
	dbprotoVariableSpecs
}

// dbprotoProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dbprotoProgramSpecs struct {
	TraceDbReadEntry     *ebpf.ProgramSpec `ebpf:"trace_db_read_entry"`
	TraceDbReadExit      *ebpf.ProgramSpec `ebpf:"trace_db_read_exit"`
	TraceDbReadvEntry    *ebpf.ProgramSpec `ebpf:"trace_db_readv_entry"`
	TraceDbReadvExit     *ebpf.ProgramSpec `ebpf:"trace_db_readv_exit"`
	TraceDbRecvfromEntry *ebpf.ProgramSpec `ebpf:"trace_db_recvfrom_entry"`
	TraceDbRecvfromExit  *ebpf.ProgramSpec `ebpf:"trace_db_recvfrom_exit"`
	TraceDbRecvmsgEntry  *ebpf.ProgramSpec `ebpf:"trace_db_recvmsg_entry"`
	TraceDbRecvmsgExit   *ebpf.ProgramSpec `ebpf:"trace_db_recvmsg_exit"`
	TraceDbSendmsgEntry  *ebpf.ProgramSpec `ebpf:"trace_db_sendmsg_entry"`
	TraceDbSendtoEntry   *ebpf.ProgramSpec `ebpf:"trace_db_sendto_entry"`
	TraceDbWriteEntry    *ebpf.ProgramSpec `ebpf:"trace_db_write_entry"`
	TraceDbWritevEntry   *ebpf.ProgramSpec `ebpf:"trace_db_writev_entry"`
}

// dbprotoMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dbprotoMapSpecs struct {
	DbEvents    *ebpf.MapSpec `ebpf:"db_events"`
	ReadBuffers *ebpf.MapSpec `ebpf:"read_buffers"`
}

// dbprotoVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type dbprotoVariableSpecs struct {
}

// dbprotoObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadDbprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type dbprotoObjects struct {
	dbprotoPrograms
	dbprotoMaps
	dbprotoVariables
}

func (o *dbprotoObjects) Close() error {
	return _DbprotoClose(
		&o.dbprotoPrograms,
		&o.dbprotoMaps,
	)
}

// dbprotoMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadDbprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type dbprotoMaps struct {
	DbEvents    *ebpf.Map `ebpf:"db_events"`
	ReadBuffers *ebpf.Map `ebpf:"read_buffers"`
}

func (m *dbprotoMaps) Close() error {
	return _DbprotoClose(
		m.DbEvents,
		m.ReadBuffers,
	)
}

// dbprotoVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadDbprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type dbprotoVariables struct {
}

// dbprotoPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadDbprotoObjects or ebpf.CollectionSpec.LoadAndAssign.
type dbprotoPrograms struct {
	TraceDbReadEntry     *ebpf.Program `ebpf:"trace_db_read_entry"`
	TraceDbReadExit      *ebpf.Program `ebpf:"trace_db_read_exit"`
	TraceDbReadvEntry    *ebpf.Program `ebpf:"trace_db_readv_entry"`
	TraceDbReadvExit     *ebpf.Program `ebpf:"trace_db_readv_exit"`
	TraceDbRecvfromEntry *ebpf.Program `ebpf:"trace_db_recvfrom_entry"`
	TraceDbRecvfromExit  *ebpf.Program `ebpf:"trace_db_recvfrom_exit"`
	TraceDbRecvmsgEntry  *ebpf.Program `ebpf:"trace_db_recvmsg_entry"`
	TraceDbRecvmsgExit   *ebpf.Program `ebpf:"trace_db_recvmsg_exit"`
	TraceDbSendmsgEntry  *ebpf.Program `ebpf:"trace_db_sendmsg_entry"`
	TraceDbSendtoEntry   *ebpf.Program `ebpf:"trace_db_sendto_entry"`
	TraceDbWriteEntry    *ebpf.Program `ebpf:"trace_db_write_entry"`
	TraceDbWritevEntry   *ebpf.Program `ebpf:"trace_db_writev_entry"`
}

func (p *dbprotoPrograms) Close() error {
	return _DbprotoClose(
		p.TraceDbReadEntry,
		p.TraceDbReadExit,
		p.TraceDbReadvEntry,
		p.TraceDbReadvExit,
		p.TraceDbRecvfromEntry,
		p.TraceDbRecvfromExit,
		p.TraceDbRecvmsgEntry,
		p.TraceDbRecvmsgExit,
		p.TraceDbSendmsgEntry,
		p.TraceDbSendtoEntry,
		p.TraceDbWriteEntry,
		p.TraceDbWritevEntry,
	)
}

func _DbprotoClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed dbproto_arm64_bpfel.o
var _DbprotoBytes []byte
