// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadHttp returns the embedded CollectionSpec for http.
func loadHttp() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_HttpBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load http: %w", err)
	}

	return spec, err
}

// loadHttpObjects loads http and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*httpObjects
//	*httpPrograms
//	*httpMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadHttpObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadHttp()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// httpSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpSpecs struct {
	httpProgramSpecs
	httpMapSpecs
	httpVariableSpecs
}

// httpProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpProgramSpecs struct {
	TraceReadEntry     *ebpf.ProgramSpec `ebpf:"trace_read_entry"`
	TraceReadExit      *ebpf.ProgramSpec `ebpf:"trace_read_exit"`
	TraceRecvfromEntry *ebpf.ProgramSpec `ebpf:"trace_recvfrom_entry"`
	TraceRecvfromExit  *ebpf.ProgramSpec `ebpf:"trace_recvfrom_exit"`
	TraceSendtoEntry   *ebpf.ProgramSpec `ebpf:"trace_sendto_entry"`
	TraceWriteEntry    *ebpf.ProgramSpec `ebpf:"trace_write_entry"`
}

// httpMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpMapSpecs struct {
	HttpEvents  *ebpf.MapSpec `ebpf:"http_events"`
	ReadBuffers *ebpf.MapSpec `ebpf:"read_buffers"`
}

// httpVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type httpVariableSpecs struct {
}

// httpObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpObjects struct {
	httpPrograms
	httpMaps
	httpVariables
}

func (o *httpObjects) Close() error {
	return _HttpClose(
		&o.httpPrograms,
		&o.httpMaps,
	)
}

// httpMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpMaps struct {
	HttpEvents  *ebpf.Map `ebpf:"http_events"`
	ReadBuffers *ebpf.Map `ebpf:"read_buffers"`
}

func (m *httpMaps) Close() error {
	return _HttpClose(
		m.HttpEvents,
		m.ReadBuffers,
	)
}

// httpVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpVariables struct {
}

// httpPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadHttpObjects or ebpf.CollectionSpec.LoadAndAssign.
type httpPrograms struct {
	TraceReadEntry     *ebpf.Program `ebpf:"trace_read_entry"`
	TraceReadExit      *ebpf.Program `ebpf:"trace_read_exit"`
	TraceRecvfromEntry *ebpf.Program `ebpf:"trace_recvfrom_entry"`
	TraceRecvfromExit  *ebpf.Program `ebpf:"trace_recvfrom_exit"`
	TraceSendtoEntry   *ebpf.Program `ebpf:"trace_sendto_entry"`
	TraceWriteEntry    *ebpf.Program `ebpf:"trace_write_entry"`
}

func (p *httpPrograms) Close() error {
	return _HttpClose(
		p.TraceReadEntry,
		p.TraceReadExit,
		p.TraceRecvfromEntry,
		p.TraceRecvfromExit,
		p.TraceSendtoEntry,
		p.TraceWriteEntry,
	)
}

func _HttpClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed http_x86_bpfel.o
var _HttpBytes []byte
