// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package probe

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type sslSslReadArgs struct {
	_   structs.HostLayout
	Buf uint64
	Len uint32
	_   [4]byte
}

// loadSsl returns the embedded CollectionSpec for ssl.
func loadSsl() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_SslBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load ssl: %w", err)
	}

	return spec, err
}

// loadSslObjects loads ssl and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*sslObjects
//	*sslPrograms
//	*sslMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadSslObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadSsl()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// sslSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslSpecs struct {
	sslProgramSpecs
	sslMapSpecs
	sslVariableSpecs
}

// sslProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslProgramSpecs struct {
	UprobeSslReadEntry   *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry *ebpf.ProgramSpec `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslWrite       *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx     *ebpf.ProgramSpec `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead     *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx   *ebpf.ProgramSpec `ebpf:"uretprobe_ssl_read_ex"`
}

// sslMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslMapSpecs struct {
	SslEvents      *ebpf.MapSpec `ebpf:"ssl_events"`
	SslReadArgsMap *ebpf.MapSpec `ebpf:"ssl_read_args_map"`
}

// sslVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type sslVariableSpecs struct {
}

// sslObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslObjects struct {
	sslPrograms
	sslMaps
	sslVariables
}

func (o *sslObjects) Close() error {
	return _SslClose(
		&o.sslPrograms,
		&o.sslMaps,
	)
}

// sslMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslMaps struct {
	SslEvents      *ebpf.Map `ebpf:"ssl_events"`
	SslReadArgsMap *ebpf.Map `ebpf:"ssl_read_args_map"`
}

func (m *sslMaps) Close() error {
	return _SslClose(
		m.SslEvents,
		m.SslReadArgsMap,
	)
}

// sslVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslVariables struct {
}

// sslPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadSslObjects or ebpf.CollectionSpec.LoadAndAssign.
type sslPrograms struct {
	UprobeSslReadEntry   *ebpf.Program `ebpf:"uprobe_ssl_read_entry"`
	UprobeSslReadExEntry *ebpf.Program `ebpf:"uprobe_ssl_read_ex_entry"`
	UprobeSslWrite       *ebpf.Program `ebpf:"uprobe_ssl_write"`
	UprobeSslWriteEx     *ebpf.Program `ebpf:"uprobe_ssl_write_ex"`
	UretprobeSslRead     *ebpf.Program `ebpf:"uretprobe_ssl_read"`
	UretprobeSslReadEx   *ebpf.Program `ebpf:"uretprobe_ssl_read_ex"`
}

func (p *sslPrograms) Close() error {
	return _SslClose(
		p.UprobeSslReadEntry,
		p.UprobeSslReadExEntry,
		p.UprobeSslWrite,
		p.UprobeSslWriteEx,
		p.UretprobeSslRead,
		p.UretprobeSslReadEx,
	)
}

func _SslClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed ssl_arm64_bpfel.o
var _SslBytes []byte
